#!/usr/bin/env bash
#

m=1
    while [ $m -le 100 ]
do
    if (( m%15 == 0 ))
    then
        echo "FizzBuzz"
    elif (( m%3 == 0))
    then
        echo "Fizz"
    elif (( m%5 == 0))
    then
        echo "Buzz"
    else
        echo "$m"
fi
    m=$((m+1))
done
