#!/usr/bin/env bash
#This script that displays all active IPv4 IPs on the machine it’s executed on
# saving all the ip addresses
ip_addresses=$(hostname -I)
# splitting them by space
ip_addresses=("${ip_addresses//" "/}")
# Print each ip address line by line
for ip in "${ip_addresses[@]}";
do
printf "%s\n" "$ip"
done
